#!/usr/bin/env python3

FRAME_TIMESTEP=0.2 #ps/frame
TIME_LIMIT=5000 #ps
FRAME_LIMIT=int(TIME_LIMIT/FRAME_TIMESTEP) if TIME_LIMIT>0 else -1
CUTOFF=0.6 # nm (RMSD)
COMMIT_FRAMES=1000
TARGET_FRACTION=0.3
